# 範例配置 - 爬取書籍網站
# 目標網站: http://books.toscrape.com/

name: "書籍爬蟲"
start_url: "http://books.toscrape.com/"

headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"

delay: 1.0

# 資料提取規則
extract_rules:
  # 書籍標題
  - field: "titles"
    type: "css"
    selector: "article.product_pod h3 a"
    attr: "title"
    multiple: true

  # 書籍價格
  - field: "prices"
    type: "css"
    selector: "p.price_color"
    multiple: true

  # 庫存狀態
  - field: "availability"
    type: "css"
    selector: "p.instock.availability"
    multiple: true

  # 評分
  - field: "ratings"
    type: "xpath"
    selector: "//p[contains(@class, 'star-rating')]/@class"
    multiple: true

# 輸出設定
output:
  format: "csv"
  path: "output/books.csv"
